services:
  sun-panel:
    image: ghcr.io/phantommaa/sun-panel/monolith:latest
    container_name: sun-panel
    volumes:
    - ./conf/conf.ini:/app/conf/conf.ini
    - ./uploads:/app/uploads
    - ./database:/app/database
    ports:
    - 3002:3002
    restart: always