# Base configuration
base:
  # Web run port. Default:3002
  http_port: 3002
  # Root URL
  root_url: http://127.0.0.1:3002
  # Database driver [mysql/sqlite(Default)]
  database_drive: sqlite
  # Enable static file server. Default:true
  enable_static_server: true
  # Enable system monitor feature. Default:true
  enable_monitor: true
  # Used as prefix to generate file url. For example, it will lookup to "/uploads/xxxx.png"
  url_prefix: /uploads/

# SQLite configuration (valid when database_drive=sqlite)
sqlite:
  file_path: ./database/database.db

# Use rclone to store files. Both support local and remote storage
rclone:
  # dir path of local or bucket of remote storage. this item config not belong to rclone
  type: local
  bucket: uploads
  conf: |-
    type = local

# JWT configuration
jwt:
  # JWT secret key
  secret: your_secret_key
  # JWT token expiration time in hours, default: 72
  expire: 72
