services:
  sun-panel:
    image: ghcr.io/phantommaa/sun-panel/monolith:latest
    container_name: sun-panel
    volumes:
      - ./conf.yaml:/app/conf.yaml
      - ./uploads:/app/uploads
      - ./database:/app/database
    ports:
      - 3002:3002
