apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sun-panel.fullname" . }}
  labels:
    {{- include "sun-panel.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sun-panel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sun-panel.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3002
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: volumn-{{ include "sun-panel.fullname" . }}-conf
              mountPath: /app/conf.yaml
              subPath: conf.yaml
      volumes:
        - name: volumn-{{ include "sun-panel.fullname" . }}-conf
          configMap:
            name: {{ include "sun-panel.fullname" . }}-conf
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
